project:
  type: book
  output-dir: docs

book:
  title: "Risk sharing"
  author: "Mizuhiro Suzuki"
  date: ""
  chapters:
    - index.qmd
    - part: base_model.qmd
      chapters:
        - base_model_theory.qmd
        - base_model_empirics.qmd
        - base_model_heterogeneity.qmd
    - part: limited_commitment_model.qmd
      chapters:
        - static_limited_commitment.qmd
        - dynamic_limited_commitment_theory.qmd
        - limited_commitment_with_storage.qmd
    - part: "Hidden information"
      chapters:
        - hidden_information_theory.qmd
    - part: "Distinguishing barriers"
    - part: "Group formation"
    - part: "Network"
  appendices:
    - base_model_us.qmd
    - coate_ravallion_reproduction.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

