# Empirics

The model developed in the previous chapter has been used extensively for empirical analyses in the literature.
There are mainly two ways the model is used: first, to test the full risk-sharing model, and second, to estimate the model parameters.
Whereas the majority of the papers in the literature takes the first approach to use the model, there are papers to use the second method, primarily for comparing the empirical relevancy of different models (e.g., @ligon2002informal, @laczo2015risk).

## Test of the full risk-sharing model

As I reviewed in the previous section, one implication of a full risk-sharing model is that individual consumption does not depend on individual income, given the aggregate resources.
In particular, from this relationship,
$$
  \frac{c_{jt}(s^t)^{-\sigma}}{c_{it}(s^t)^{-\sigma}} = \frac{\lambda_i}{\lambda_j} \quad \forall s^t, \forall t.
$$
by dropping $s^t$ from the equation for simplicity and taking the logarithms, I obtain
$$
\begin{aligned}
  -\sigma \log(c_{jt}) + \sigma \log(c_{it}) &= \log(\lambda_i) - \log(\lambda_j) \\
  \Leftrightarrow \log(c_{it}) &= \frac{1}{\sigma} \left( \log(\lambda_i) - \log(\lambda_j) \right) + \log(c_{jt}) \\
  \Leftrightarrow N \log(c_{it}) &= \frac{1}{\sigma} \left( N \log(\lambda_i) - \sum_j \log(\lambda_j) \right) + \sum_j \log(c_{jt}) \\
  \Leftrightarrow \log(c_{it}) &= \frac{1}{N} \sum_j \log(c_{jt}) + \frac{1}{\sigma} \log(\lambda_i) - \frac{1}{\sigma} \frac{1}{N} \sum_j \log(\lambda_j)  .
\end{aligned}
$$
For the right-hand side of the equation, the first term is the village-average of log of consuption, and be controlled for by village-time fixed effects.
The second term captures the effect of the household's Pareto weight on his consumption, and can be controlled for by individual fixed effects.
And the last term is simply a constant.

Following this relationship, we expect that other factors such as idiosyncratic shocks such as income shocks of each household do not impact his consumption if other variables in the equation are controlled for.
Hence, studies testing a full risk-sharing model include such shocks in the equation and check whether the coefficient of the shocks are statistically significant or not.
If they are, then that means the failure of full risk sharing.

Specifically, the full risk-sharing model usually is tested by running the following equation:
$$
  \log(c_{it}) = \alpha + \beta \log(y_{it}) + \nu_{vt} + \mu_i + \epsilon_{it},
$$
where $\nu_{vt}$ is a village-time fixed effect and $\mu_i$ is a household fixed effect. 
Many previous studies have found that the estimate of $\beta$ is statistically significant (eg. @deaton1992understanding, @Townsend1994), which has led to development of the later studies investigating the cause of failure of full risk sharing.
Similar tests are conducted with U.S. data as well (reviewed [here](base_model_us.qmd)), where the focus is on the test of a complete market, not risk-sharing per se.

## Structural estimation of parameters

The other main way to use the full risk-sharing model empirically is to estimate the structural parameters.
Usually the parameters themselves are not the main objects of interest, but rather the models are structurally estimated to compare the model fit with other models.
For example, @ligon2002informal estimate the model with the non-linear squared error method, and @laczo2015risk estimates the full risk-sharing model with the simulated maximum likelihood method.
Both of them use the objective values from the estimation to see how much the model explains the data compared to other models such as the limited commitment model.

Here, I follow the framework in @laczo2015risk to demonstrate how the likelihood function is derived.

### Introducing measurement errors

First, I introduce to the full risk-sharing model the measurement error in consumption, which is assumed to be multiplicative and log-normally distributed. 
In particular, I denote observed consumption, $c_{it}^*$ as $c_{it}^* = c_{it} \exp(\varepsilon_{it}^c)$, where $\varepsilon_{it} \sim N(0, \gamma_c^2)$ is the measurement error which is i.i.d. across households and time.
With this, the observed village-average consumption, $c_{vt}^*$ is so that
$$
\begin{aligned}
  \log(c_{vt}^*) 
  &= \frac{1}{N} \sum_i \log(c_{it}^*) \\
  &= \frac{1}{N} \sum_i \log(c_{it}) + \frac{1}{N} \sum_i \varepsilon_{it}^c \\
  &= \log(c_{vt}) + \frac{1}{N} \sum_i \varepsilon_{it}^c \\
  &= \log(c_{vt}) + \varepsilon_{vt}^c,
\end{aligned}
$$
where the village consumption measurement error is defined as $\varepsilon_{vt}^c \equiv \frac{1}{N} \sum_i \varepsilon_{it}^c$.
Substituting these into $\log(c_{it}) - \log(c_{i, t - 1}) = \log(c_{vt}) - \log(c_{v, t - 1})$, I obtain
$$
  \log(c_{it}^*) - \log(c_{i, t - 1}^*) = \log(c_{vt}^*) - \log(c_{v, t - 1}^*) + \left(\varepsilon_{it}^c - \varepsilon_{vt}^c - (\varepsilon_{i, t - 1}^c - \varepsilon_{v, t - 1}^c) \right).
$$

### Likelihood function

Since $\varepsilon_{it} \sim N(0, \gamma_C^2)$, I get $\varepsilon_{vt} \sim N(0, \frac{\gamma_C^2}{N})$, and note that $Cov(\varepsilon_{it}, \varepsilon_{vt}) = \frac{\gamma_C^2}{N}$.
With the independence across periods and households of measurement errors, I obtain
$$
  Var(\varepsilon_{it}^c - \varepsilon_{vt}^c - (\varepsilon_{i, t - 1}^c - \varepsilon_{v, t - 1}^c) ) 
  = 2\left(\gamma_C^2 + \frac{\gamma_C^2}{N} - 2\frac{\gamma_C^2}{N} \right) 
  = 2 \gamma_C^2 \left(1 - \frac{1}{N} \right).
$$

Therefore, the likelihood function is

$$
  L(\theta) = \prod_{i} \prod_{t = 2}^{T} f \left( \log \left( \frac{c_{it}^*}{c_{i, t - 1}^*} \right) - \log \left( \frac{c_{vt}^*}{c_{v, t - 1}^*} \right), \theta \right) ,
$$
and the log likelihood function is
$$
  l(\theta) = \sum_{i} \sum_{t = 2}^{T} \log \left(f \left( \log \left( \frac{c_{it}^*}{c_{i, t - 1}^*} \right) - \log \left( \frac{c_{vt}^*}{c_{v, t - 1}^*} \right), \theta\right) \right),
$$
where $f(x, \theta)$ is the density function of $x \sim N \left(0, \sqrt{ 2 \gamma_C^2 \left(1 - \frac{1}{N} \right)} \right)$, and $\theta$ is a parameter to estimate (here, $\theta = \gamma_C$).
In estimation, I find the parameter to maximize $l(\theta)$.

Without assuming that the model is correctly specified but assuming that there is no autocorrelation, the standard error of the parameter is $A(\widehat{\theta})^{-1} B(\widehat{\theta}) A(\widehat{\theta})^{-1}$, where $A(\widehat{\theta})$ is the Hessian matrix of the log-likelihood function and $B(\widehat{\theta})$ is the outer product of scores (= gradient of log likelihood).

## References
