# Theory

I first review the full risk-sharing model.
Chapter 8 of @bardhan1999development provides a great textbook-treatment of the model.

## Settings

Suuposed that there are $N$ households in a village. Each household maximized its expected lifetime utility: $$
  E \left[ \sum_{t = 1}^{\infty} \delta^t u (c_{it}) \right],
$$
where $\delta$ is the discount factor, $u$ is instantaneous preference of households (note that here I assume homogeneous preference), and $c_{it}$ is consumption by household $i$ at time $t$.
Assume that there is no saving.

For income, let $s^t = (s_1, \dots, s_t)$ the history of income states from time $1$ to $t$, and let $y_{it}(s_t)$ be household $i$'s income at time $t$ and state $s_t$.
Assume that the income process is independent across households.

With these, I find the Pareto-optimal allocations.
For this, a weighted sum of households' expected lifetime utilities is maximized.
In other words, a social planner solves the following maximization problem:
$$
  \max_{\{c_{it}(s^t)\}} \quad \sum_i \lambda_i \sum_{t = 1}^{\infty} \sum_{s^t} \delta^t \pi(s^t) u(c_{it}(s^t))
$$ subject to the resource constraint $$
  \sum_i c_{it}(s^t) \le \sum_i y_{it}(s_t) \quad \forall s^t, \forall t,
$$
where $\lambda_i$ is the Pareto weight of $i$, $\pi(s^t)$ is the probability that the history $s^t$ is realized, and $c_{it}(s^t)$ is $i$'s consumption under the history $s^t$.

## Optimization condition

Solving this maximization problem, we see that, for any two households $i$ and $j$ in the village, the following holds: 
$$
  \frac{u'(c_{jt}(s^t))}{u'(c_{it}(s^t))} = \frac{\lambda_i}{\lambda_j} \quad \forall s^t, \forall t.
$$

If I assume the utility function to take the CRRA form, that is, $$
  u(c_{it}) = \frac{c_{it}^{1 - \sigma} - 1}{1 - \sigma},
$$
then
$$
  u'(c_{it}) = c_{it}^{- \sigma},
$$
and thus I get
$$
\begin{aligned}
  &\quad \frac{c_{jt}(s^t)^{-\sigma}}{c_{it}(s^t)^{-\sigma}} = \frac{\lambda_i}{\lambda_j} \quad \forall s^t, \forall t \\
  &\Leftrightarrow \frac{c_{jt}(s^t)}{c_{it}(s^t)} = \left( \frac{\lambda_i}{\lambda_j} \right)^{-1/\sigma} \quad \forall s^t, \forall t.
\end{aligned}
$$

## Model implications

The relationship above means that the ratio of consumption between any two households is constant across time and states, where households with larger $\lambda$ enjoyes higher consumption.
Another way to interpret this expression is that, by taking logarithms and taking a first-order difference, I et
$$
\log(c_{it}(s^t)) - \log(c_{i, t - 1}(s^{t - 1})) =  \log(c_{jt}(s^{t})) - \log(c_{j, t - 1}(s^{t - 1})) \quad \forall s^t, s^{t-1}, \forall t,
$$
which means that the growth rate of consumption is identical for any households in the village, in any state and time.

Also, under a full risk sharing, consumption does not depend on the individual income:
it is determined by their Pareto weights and the aggregate resources.
This is the basis of the empirical test of a full risk-sharing model, as shown in the next chapter.

## Rerefences