# Static limited-commitment model

In a *static* limited commitment model, transfer rules are not allowed to depend on past states.
The repeated game is used in the analysis, and @coate1993reciprocity provides a simple and clear framework.

## Model

I introduce a statsic limited commitment model following the set up in @coate1993reciprocity.

[TBA]

## Related papers

### @Kimball1988

In this paper, he provides a framework for risk-sharing with limited commitment and conducts numerical analyses to see (i) under what parameter values enforceability constraints are satisfied (and hence some form of transfers happens), and (ii) under what parameter values full risk-sharing is achieved.
Interestingly, in his formulation of the problem, he does not use the repeated game but instead uses the dynamic optimization, which looks closer to the dynamic limited commitment model (introduced below) in which transfers can depend on past states.
However, Kimball explicitly rules out the possibility of consumption depending on the past states (p.226), which makes the framework a static limited commitment model.

<!-- The paper says Table 1 shows that the enforceability constraints tend to be satisfied with reasonable parameters and Table 3 shows that full risk-sharing can be achieved with reasonable parameters. -->
<!-- I am not sure (i) what the expression for $W(P)$ on p.226 is, (ii) how to derive (6), and (iii) how to get numbers on Table 3. -->

The main motivation in this paper is to explain why farmers had scattered plots in Medieval England.
Some say this is for insurance (as a form of income diversification), but Kimball argues that this is unlikely since, as shown in the paper, risk-sharing among farmers as informal insurance can be sustained.
Thus, he argues that, rather than relying on the costly income diversification (eg. travel time), farmers should use risk-sharing for insurance.

### @coate1993reciprocity

Like @Kimball1988, this paper also considers a risk-sharing model with limited commitment model.
Unlike @Kimball1988, however, their framework is based on an infinite-period repeated game:
in each period, players either follow a transfer schedule or renege and will stay in autarky forever.
Under symmetric income distribution, they compare first-best transfers under full risk-sharing and best implementable transfers (best in the sense that the transfers that maximize the expected utilities).

The problem considered in the paper is to maximize the average expected utility of a household (by symmetry, a transfer schedule that maximizes the average expected utility of one household maximizes that of the other household), subject to the following *implementability constraints*:

\begin{align*}
  u(y_i) - u(y_i - \theta_{ij}) &\le (v^A(\Theta) - \overline{v}) / r \quad \text{for all } (i, j) \\
  u(y_j) - u(y_j + \theta_{ij}) &\le (v^B(\Theta) - \overline{v}) / r \quad \text{for all } (i, j),
\end{align*}

where $y$ is income, $\theta_{ij}$ is the transfer from A to B when the state is $(i, j)$, $\Theta$ is the entire transfer schedule, or *informal insurance arrangement*, $\overline{v}$ is the value under autarky, and $r$ is the discount rate.
Using this framework, they examine (i) how the best implementable (ie. under the implementability constraints) insurance arrangement and the full risk-sharing insurance arrangement differ, and (ii) how the best implementable insurance arrangement changes with exogenous variables of the model (discount rate and correlation in income realizations).
Also, they conduct numerical exercises to show how changes in exogenous variables affect the insurance arrangement.
The numerical exercises 

As suggestions for future research (I mean, "future" from their perspective), they provide three possible directions to extend their model:

1. to allow non-stationary insurance arrangements, which can depend on both current and past income realizations;
2. to allow households to save;
3. to allow households' income to depend on its work effort which others in the community cannot observe.

Interestingly, all of these three extensions have been achieved by later works:
(1) by, for example, @ligon2002informal, (2) by, for example, @Ligon2000, and (3) by, for example, XXX.

### Difference between @Kimball1988 and @coate1993reciprocity

The main difference between this paper and @Kimball1988 is that, 

- while @Kimball1988 identifies the conditions (i) for risk-sharing institutions to exist and (ii) for full risk-sharing to be achieved,
- @coate1993reciprocity investigates the properties of the best implementable insurance arrangement (ie. how this is different from the insurance arrangement under full risk-sharing and how this arrangement changes as exogenous variables vary).

## References
